name: Keep Render Service Alive

on:
  schedule:
    # This runs every 14 minutes
    - cron: '*/10 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping Render Service
      run: |
        curl -s https://blacksignals101.onrender.com > /dev/null
